ALTER TABLE tokens ADD COLUMN portal_key TEXT NOT NULL DEFAULT '';
ALTER TABLE tokens ADD COLUMN portal_url TEXT NOT NULL DEFAULT '';
ALTER TABLE tokens ADD COLUMN portal_api_root TEXT NOT NULL DEFAULT '';
ALTER TABLE tokens ADD COLUMN portal_apps TEXT NOT NULL DEFAULT '';
ALTER TABLE tokens ADD COLUMN portal_stories_root TEXT NOT NULL DEFAULT '';
