address = "127.0.0.1"
port = 3324
public_base_url = "http://localhost:3324"

[[arcgis_portals]]
key = "geojobe-agol"
label = "https://geo-jobe.maps.arcgis.com"
portal_url = "https://geo-jobe.maps.arcgis.com"
api_root = "https://geo-jobe.maps.arcgis.com/sharing/rest"
portal_apps = "https://geo-jobe.maps.arcgis.com/apps"
stories_root = "https://storymaps.arcgis.com/stories"
client_id = "f1CeTunauIhPYV6U"

[[arcgis_portals]]
key = "enterprise113"
label = "https://enterprise113.geopowered.com"
portal_url = "https://enterprise113.geopowered.com/portal"
api_root = "https://enterprise113.geopowered.com/portal/sharing/rest"
portal_apps = "https://enterprise113.geopowered.com/portal/apps"
stories_root = "https://enterprise113.geopowered.com/portal/apps/storymaps/stories"
client_id = "6FpaxEjkUwgYwk4I"
